FROM ubuntu:24.04

ARG ver=2.5.10
WORKDIR /root/

RUN apt update && apt install -y liblz4-dev liblzo2-dev libpam0g-dev libssl-dev

COPY openvpn-${ver} /usr/local/openvpn

RUN ln -s /usr/local/openvpn/sbin/openvpn /usr/bin/openvpn

RUN apt-get -y autoremove && apt-get -y clean && apt-get -y autoclean

